---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: false

platforms:
- name: debian-wheezy
  driver_config:
    box: debian-wheezy
    box_url: http://projects.tsuntsun.net/~nabeken/boxes/vagrant-debian-wheezy.box

suites:
- name: default
  run_list:
  - recipe[debian]
  - recipe[postgresql::ruby]
  - recipe[postgresql::server]
  - recipe[pdns_test::default]
  - recipe[pdns::backup]
  - recipe[minitest-handler]
  encrypted_data_bag_secret_key_path: test/integration/secret_key
  attributes:
    pdns:
      axfr_ips:
      - "192.168.1.200"
      - "192.168.1.201"
      db_password: "pdns"
      backup:
        repository: "https://gist.github.com/a59c16a1c595e061c314.git"
    postgresql:
      password:
        postgres: "test"
